### ISSUE TITLE
Post GSA suggestions

### ISSUE THREAD

**Issue by AZlaserchron** [CIRDLES/ET_Redux#110]
Since GSA has came and went I have a few suggestions to make the workflow a bit easier. These ideas are for cosmetic and overall ease of use.

1. Be able to add and remove unknown spots in groups rather than individually. Being able to highlight a bunch to add to the removed fractions area. This feature would be very useful when creating weighted means. Even if we were able to use this feature in the sample dates window so it is easier to select the population of grains you want for the weighted mean.

2. Adjusting the size of windows when they appear. Like at gsa our live data window was so huge that it was difficult to maneuver. Make the windows a more reasonable size.

**Comment by bowring** [comment]
The first item is addressed partially in v3.6.7 (3 Oct 2016) with a new menu item for sample dates under weighted means that toggles sorting the fractions in a weighted mean by date in the left hand panel.  Further work on designing the appropriate user interface is requested for a future issue.

The second item is not realistic in my opinion.  The live view was specifically designed for a large monitor and not to be used with a laptop, etc that doesn't support at least 2100 x 1300 pixels.  All other windows require at least 1200 x 800 pixels.  We don't support smaller resolutions.
