### ISSUE TITLE
Error importing legacy TIMS data

### ISSUE THREAD

**Issue by riouxm** [CIRDLES/ET_Redux#111]
When using the csv import for legacy data, I am getting an error message. I am using the MIT legacy csv template. I then go to new sample from legacy analysis>ID TIMS legacy analysis (MIT) and select the csv. When I do this, I get an error saying "Document error: Premature end of file". If I press okay, it then takes me to the usual csv import screen and still seems to work otherwise. I am running ET_Redux 3.6.6. I was not able to attach a csv to this report, but can e-mail one of the files.

**Comment by bowring** [comment]
This issue is corrected in release 3.6.7 slated for 3 October.
