### ISSUE TITLE
Unable to open PROBABILITY-DENSITY.svg files in AI

### ISSUE THREAD

**Issue by riouxm** [CIRDLES/ET_Redux#113]
I am getting an error message when I try to open PROBABILITY-DENSITY.svg files created by redux in Illustrator. The error reads "The operation cannot be completed because of an unknown error. [CANT]" To test if this was a general problem, I generated a svg file of a concordia plot, and I was able to open this in Illustrator without any problem. It seems to be a problem with the files being created for the probability density plots. I am running Redux 3.6.6 and IllustratorCS5.1.

**Comment by bowring** [comment]
I get the same error with CS5(399), but it works fine with CC.2015.3, so I am not going going to spend time on this as it is likely an Adobe issue, not an ET_Redux issue
