### ISSUE TITLE
Redux plotting histogram incorrectly

### ISSUE THREAD

**Issue by riouxm** [CIRDLES/ET_Redux#114]
Redux appears to be plotting a histogram incorrectly. The sample has 22 data points, but the histogram bars only account for 21 data points.

I cannot attach the redux file here, but will e-mail it (sample 06-12).

The problem occurs when I set the histogram bin width to 50. The plot appears to miss the data point with a date of 1059 Ma.

**Comment by bowring** [comment]
I can replicate this.  The workaround for now is to toggle the lock button for the histograms and it repaints correctly.

**Comment by noahmclean** [comment]
Matt, you are up for the award for most observant beta-tester ever.

**Comment by riouxm** [comment]
That sounds better than the “most annoying Redux user”, which I might also have a shot at.
