### ISSUE TITLE
Problem opening  3.6.9 on Windows

### ISSUE THREAD

**Issue by AZlaserchron** [CIRDLES/ET_Redux#120]
I have tried multiple times to open redux version 3.6.9. I get to the home screen but when I select LA-ICPMS nothing happens. It doesn't crash, it just doesn't open....

**Comment by bowring** [comment]
I assume you are saying that clicking Project / New Project from Raw Data/ LAICPMS doe not work for you?  It works here on Mac, anyway - no windows boxes available here.  Try opening a terminal and typing "java -jar ET_Redux-3.6.9.jar" and then send me the text of any errors that appear in the window when you access the LAICPMS menu item.

**Comment by AZlaserchron** [comment]
The error I just received was 
Error: Unable to access jarfile ET_Redux-3.6.9.jar

So it wont even open for me... Could very well be my machine

**Comment by bowring** [comment]
Make sure you are executing the java command in the folder that has ET_Redux.

**Comment by bowring** [comment]
Confirmed it is a Windows issue - will fix directly.
