### ISSUE TITLE
Filters resetting in Live view

### ISSUE THREAD

**Issue by AZlaserchron** [CIRDLES/ET_Redux#129]
When filters for discordance, reverse discordance, and uncertainties are set they are reset to the default values after every new grain. If they could lock after you set them so we don't have to keep adjusting them this would be great. Also if we could set a default filter for these before we begin the run.

**Comment by bowring** [comment]
@AZlaserchron - I am not able to replicate this behavior - the sliders do not reset.  Can you supply a small data set where this is happening?

**Comment by AZlaserchron** [comment]
@bowring It seems to happen frequently, I will run the live reduction today and test it out again. Maybe it was just a few samples, but I will try again.
