### ISSUE TITLE
Gray text in results table

### ISSUE THREAD

**Issue by riouxm** [CIRDLES/ET_Redux#134]
New samples in the results table are remaining gray even after the initial data is input. Noah confirmed this behavior on his computer and e-mailed Jim an example redux file a couple weeks ago. I have since noticed that if I open and close the sample dates window, this fixes the problem and all fractions that contain data turn black.

**Comment by bowring** [comment]
Version 3.6.13 fixes this issue.

**Comment by riouxm** [comment]
I just installed 3.6.13 and I am still seeing this issue. When Pb data is first imported for a fraction the text in the report table remains grayed out. The work around I described above of opening the kwiki or sample dates window still seems to work.

**Comment by bowring** [comment]
We are talking TIMS, right?

**Comment by riouxm** [comment]
Yes.
