### ISSUE TITLE
Sample Dates button not working

### ISSUE THREAD

**Issue by riouxm** [CIRDLES/ET_Redux#142]
Just updated to ET_Redux 3.6.14. The "Sample Dates" button does not seem to work in this version. When I press the button, it becomes grayed out, but the "Sample Dates" window does not open. The "Sample Dates" button stays grayed out until I open a new sample. I tried the new version on both a windows machine and my mac and had the same problem on both.

**Comment by bowring** [comment]
This is a side-effect of an experiment with McLEan Regression - short term
fix is to reject all bad fractions.  Hotfix on its way soon.

**Comment by bowring** [comment]
Coming this weekend - e=please excuse the delays
