### ISSUE TITLE
Kwiki slider bars not sliding

### ISSUE THREAD

**Issue by noahmclean** [CIRDLES/ET_Redux#148]
The slider bars in the Kwiki tab on the fraction window of TIMS Redux do not respond to clicking and dragging.  They only seem to budge (a little) if the cursor is moving when you click on the slider, but then they immediately cease moving again.  I'm using version 3.6.16 on a Mac.

**Comment by bowring** [comment]
This appears to be a side-effect f changes in Java.  I went back to version jdk1.8.0_51 and the sliders work.  I have implemented a work-around that restores this functionality in the next release.

**Comment by noahmclean** [comment]
Cool, thanks!
