### ISSUE TITLE
Unable to select fractions in this .redux file

### ISSUE THREAD

**Issue by NicoleRayner** [CIRDLES/ET_Redux#166]
Hi Jim,

As discussed today, I am unable to select fractions in this redux file.  Note that the small "N" in the left-most column is alternately greyed out or not present.  Not sure why this file is doing this.  Let me know if there is anything else I can provide to help clarify this.

[1563cannot select rows.zip](https://github.com/CIRDLES/ET_Redux/files/2480271/1563cannot.select.rows.zip)

**Comment by bowring** [comment]
Please supply info on how this file was created including source files ... somehow there are two leading columns named "Fraction".

**Comment by NicoleRayner** [comment]
Our data is processed as follows: 
Raw Triton .exp data files are brought into a custom program that rectifies issues (like the date style, using hyphens not dashes) and resaves as .exp.   T
hey are brought into Tripoli and saved as .trip files. then exported as .xml.  
Attached are the .trip and .xml files for the first 4 fractions of this .redux file.
[1563 Tripoli files for testing.zip](https://github.com/CIRDLES/ET_Redux/files/2525862/1563.Tripoli.files.for.testing.zip)
[1563 xml files for testing.zip](https://github.com/CIRDLES/ET_Redux/files/2525866/1563.xml.files.for.testing.zip)

**Comment by NicoleRayner** [comment]
I just reimported ALL the fractions and it worked fine.  Must have just been some little gremlin that crept in for some reason but now is gone.  Thanks for looking into this.  
I used the latest version - lightning fast!

**Comment by bowring** [comment]
Resolved.
