### ISSUE TITLE
Sample date interpretations for U-series bugged v.3.6.84

### ISSUE THREAD

**Issue by PeterChutcharavan** [CIRDLES/ET_Redux#181]
I am having trouble viewing U-series carbonate data in the "evolution" and "Age vs Init Delta" plots. The issues I have observed are as follows:

(1) Initially, both plots are empty. I have to click "tight" in order to see the data

(2) If I try to zoom out all the way on the "evolution plot" it crashes to a blank image. 

(3) There is a similar problem with the "Age vs Init Delta" plot where it becomes next to impossible to zoom back into the plotted data and the graph eventually freezes.

(4) The "Seawater & OpenSys Isochron" button is not working.

**Comment by bowring** [comment]
@PeterChutcharavan - Thanks for looking.
1) be sure you have latest version 3.6.84
2) find and delete these two files: ReduxLabData.ser and ReduxPersistentState.ser
3) fire up redux
4) re-import data file
5) let me know how that goes

**Comment by bowring** [comment]
ps. - no instructions yet - sorry;  right mouse click on graphs for additional options

**Comment by PeterChutcharavan** [comment]
Hi @bowring,

Normally, I just download the .jar file when I run ET_Redux, do I need to download the source code as well? I downloaded the source code this time (already running 3.6.84) and deleted the files you suggested. It did not change anything BUT in the process I realized that most of these problems go away when I run ET_Redux on Mac as opposed to Windows, with the exception of issue #3.

**Comment by bowring** [comment]
not related to source code.

those files exist on your hard drive and are written by ET_Redux 

zoom issue noted ... for now use the "tight" button

working on bug fixes and improvements

**Comment by PeterChutcharavan** [comment]
Okay, yup I found where the files are on my (PC) hard drive. Deleted the two .ser files as you suggested and still had issues 1,2 & 4 so I can confirm those issues are associated with running ET_Redux on windows. Thanks again!

**Comment by bowring** [comment]
what version of java on windows?  needs to be 1.8 not higher;  can you confirm from command line?

**Comment by PeterChutcharavan** [comment]
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)
