### ISSUE TITLE
Add [232Th/238U] activity ratio to legacy U-series carbonate template

### ISSUE THREAD

**Issue by PeterChutcharavan** [CIRDLES/ET_Redux#182]
Based on the legacy U-series carbonate template, it seems like the [232Th/238U] activity ratio is calculated using the 232Th/238U * 10^5 atomic ratio in ET redux. This atomic ratio is only reported in a few of the older (i.e. pre-2000s) U-series papers, so it would be better to have the [232Th/238U] field not be dependent on a reported “232Th/238U * 10^5” atomic ratio. Therefore, I would recommend including the reported [232Th/238U] activity ratio and uncertainty in the U-series carbonate template. Also, [232Th/238U] should not be multiplied by “10^5”, this is only done for the atomic ratio.

**Comment by noahmclean** [comment]
Hi Peter,
Thanks for the suggestion.  Here is Jim's fix: 

In the template, replace the word "atomic" with "activity" in the headings for columns P and Q with "activity" then cut/paste the [232Th/238U] activity ratio and uncertainty as you suggest.  Jim will add code to Redux to detect this switch and to treat this as an activity ratio coming in.  

In the Redux code that performs U-series calculations, we store and treat all isotope ratios as atom ratios, converting with the user-specified decay constants from the Physical Constants Model."  That means that once a number is input, it propagates throughout the code correctly into the data table, age calculations, etc.

**Comment by PeterChutcharavan** [comment]
Hi Noah,

Thanks, that explanation helps a lot with my understanding of the workflow for propagating the U-series data. Are we still keeping the 232Th/238U * 10^5 atomic ratio columns and just moving them to columns R and S?

**Comment by bowring** [comment]
We are not adding columns, rather giving the user the ability to customize those two columns to contain all atomic ratios (current setup) or all activity ratios and to signal their choice by changing the column headers.  These templates originated from your lab, and we are trying to ensure that all the existing data files would not have to be redone.

**Comment by PeterChutcharavan** [comment]
I see...thanks for the clarification.

**Comment by bowring** [comment]
Does that work for you - at least in the short run?

**Comment by PeterChutcharavan** [comment]
Yes, that will work just fine! I had forgotten that each source is uploaded individually, so I can just switch the column heading depending on whether the atomic or activity ratio for 232Th/238U is reported for that source.

**Comment by bowring** [comment]
Correct - note this is not yet available!  stay tuned

**Comment by bowring** [comment]
Peter - please make a file both ways so I can test ... thanks!

**Comment by PeterChutcharavan** [comment]
Hi Jim,

Here are two test files. Ch91_1 has 232Th/238U atomic ratios and Ch91_2 is the activity ratios. Please note that the activity ratios are not multiplied by 10^5 (this is just something that has been done for the atomic ratios in previous coral U-series papers).

Hope this helps!

Peter

[Ch91_1.txt](https://github.com/CIRDLES/ET_Redux/files/3393080/Ch91_1.txt)
[Ch91_2.txt](https://github.com/CIRDLES/ET_Redux/files/3393082/Ch91_2.txt)

**Comment by bowring** [comment]
looks like they are reversed - 1 = activity and 2 = atomic in the column headers for P, Q.

as a sanity check - do any of our existing file even populate P and Q?

**Comment by PeterChutcharavan** [comment]
Yes, you are correct. I had then switched around in my post (sorry!). In the published databases (i.e. Dutton and Lambeck 2012, Hibbert et al., 2016) only a handful of the papers report the 232Th/238U atomic ratio, which is why most of the files don't populate those columns. The [232Th/238U] activity ratios are also reported in some papers as well, but there was not a column for this in the 2012/2016 databases.

**Comment by bowring** [comment]
so do any of the actual text files we have contain this data?

**Comment by bowring** [comment]
Question: first sample from our example
atomic ratio = 3.07 e-11 
activity ratio = 3.07 e-11 * lambda232 / lambda238 = 9.79 e-12

your table shows activity ratio of 0.969

what am I missing?

see:
[RelativeAbundances_v1.pdf](https://github.com/CIRDLES/ET_Redux/files/3412642/RelativeAbundances_v1.pdf)

**Comment by PeterChutcharavan** [comment]
Looks like it was another typo on my part. The "activity" file had the atomic ratios and vice versa (i.e. 0.969 is the 232Th/238U *10^5 atomic ratio for the first analysis in that file. I've corrected the error and have uploaded a fresh copy of the files here. Ch91_1 should still be the activity ratio and Ch92_2 should be atomic, let me know if there are any other problems.

-Peter

[Ch91_1.txt](https://github.com/CIRDLES/ET_Redux/files/3412746/Ch91_1.txt)
[Ch91_2.txt](https://github.com/CIRDLES/ET_Redux/files/3412747/Ch91_2.txt)

**Comment by PeterChutcharavan** [comment]
Regarding the previous question:

Files 1, 11, 56, 65, and 86 have the 232Th/238U atomic ratios. You are correct, none of the other text files have [232Th/238U] activity ratios, which is why I had to make a separate file for testing purposes. I can make a few more if that will help.

**Comment by bowring** [comment]
First row example: there is still a magnitude mismatch.  Shouldn't the atom ratio be 9.69e-11 actual and in the text file (multiplied by 10^5) be 9.69e-6 ?  That would yield an actual activity ratio of 3.07e-11, shown in the text file as 3.07e-6 after multiplying by 10^5?

**Comment by bowring** [comment]
also, I don't have files with numbered names, rather 'anderson' etc. - can you map them for me - the examples you mention above or send me the numbered-name files?  thanks
