### ISSUE TITLE
upper intercept regression

### ISSUE THREAD

**Issue by riouxm** [CIRDLES/ET_Redux#22]
There is a bug with the upper intercept regressions when using ET_redux 3.0.4 to regress legacy data entered as a UCSB LASS project. The regressions work, but when I select "truncate regression curve below concordia" in the concordia plot display settings, the regression line disappears completely.

**Comment by bowring** [comment]
@riouxm - I can only reproduce that behavior when upper = lower as in our synthetic dataset CM2; send me your .redux file privately as I know it is not yet published.
