### ISSUE TITLE
Fractionation Model Error   

### ISSUE THREAD

**Issue by dannyhnatyshin** [CIRDLES/ET_Redux#222]
Hello

I was trying to update a Fractionation Model in ETRedux but when I try to import/export a Pb (or U) Fractionation model as a XML file I get the following error "XML data file does not conform to schema". 

Any idea on how to address this error?

Thanks 
Danny

**Comment by bowring** [comment]
Please include the xml files.  We’re they generated by Tripoli?

**Comment by dannyhnatyshin** [comment]
So what I was trying to do was: ET Redux --> Lab Data --> UPb --> Fractionation Models --> Fractionation Models --> Edit new AlphaPb Model --> put in values for "Model Name" "alpha Pb" and "one sigma abs" --> Export AlphaPb Model as XML file
Then the "XML data file does not conform to schema" error pops up

I assume this is how we create new models in ET Redux (So that they are available in the "Choose Model" dropbox)? Or am I missing somthing? 

Thanks for being so quick!
Danny

**Comment by bowring** [comment]
Works for me.  Are you using version 3.7.1 and connected to the internet?  What *exact* values are you entering?  Are you copy-pasting or typing? (sometimes pastes have hidden characters)

**Comment by bowring** [comment]
BTW, under Help menu you can create a Github issue that sends environment details.  Thanks for using issues!

**Comment by dannyhnatyshin** [comment]
It was 3.7.1. But I decided to redownload it and now it works! The good old turn it off and on approach. Thanks for helping! If the error pops up again I'll let you know!
