### ISSUE TITLE
Loading U-Pb redux files in ET_Redux 3.3.3 discards user-input Th/U magma values

### ISSUE THREAD

**Issue by brenhinkeller** [CIRDLES/ET_Redux#42]
I observed this issue when moving a .redux file saved by U-Pb_Redux 2.7.55 on a front-end mass spec PC to ET_Redux 3.3.3 on a mac laptop, but it seems other users have experienced similar problems with other version combinations, so this issue may be more general.

**Comment by bowring** [comment]
please supply file example save by 2.7.55 - you can zip and email it to me
at bowring@gmail.com

On Thu, Jan 14, 2016 at 5:36 PM, brenhinkeller <notifications@github.com>
wrote:

> I observed this issue when moving a .redux file saved by U-Pb_Redux 2.7.55
> on a front-end mass spec PC to ET_Redux 3.3.3 on a mac laptop, but it seems
> other users have experienced similar problems with other version
> combinations, so this issue may be more general.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CIRDLES/ET_Redux/issues/42>.
>



-- 
Jim Bowring
C. Richard Crosby Distinguished Teaching Co-Chair
Principal Investigator, www.CIRDLES.org, www.github.com/cirdles

Computer Science
College of Charleston
66 George Street
Charleston, SC 29424

Google Voice: 843.608.1399 (preferred)
Google Email: bowring@gmail.com

Office:
Harbor Walk East (360 Concord Street) Room 308
843.953.0805
http://stono.cs.cofc.edu/~bowring/
bowringj@cofc.edu

R. Buckminster Fuller (1972):
If humanity is to survive aboard our planet, it must become universally
literate and preoccupied with inherently cooperative Comprehensive
Anticipatory Design Science in which every human is concerned with
accomplishing the comfortably sustainable well-faring of all other humans.

**Comment by brenhinkeller** [comment]
File sent, but seems to open without problem now. I'm not sure if this (and other anecdotes) were caused by user error, corruption, or a very unusual sequence of operations but I can't seem to reproduce it. Unless someone else has observed and can reproduce, there's probably no need to keep the issue open.
