### ISSUE TITLE
Secondary RM designation not 'sticky'

### ISSUE THREAD

**Issue by noahmclean** [CIRDLES/ET_Redux#65]
Open the 'Project Manager' or process new raw data to bring up the 'Project Manager' window, then change the role of one or more of the 'Unknowns' to 'Secondary RMs'.  The dropdown menu reads 'Secondary RM' until you hit 'Save Project', when the roles spontaneously switch back to 'Unknown'.  The role should stay as 'Secondary RM'.

**Comment by bowring** [comment]
@noahmclean: Found the issue - it is due to a missed update of a string referring to "standard" vs the new "reference material. Fix will appear in next release.

**Comment by noahmclean** [comment]
Great, thanks!
