### ISSUE TITLE
error on fraction download from geochron

### ISSUE THREAD

**Issue by noahmclean** [CIRDLES/ET_Redux#71]
Downloading a (randomly selected) aliquot from geochron (http://geochron.org/upstreamviewfile.php?pkey=7282) and loading it into Redux via Sample -> New Compilation of Aliquots into SuperSample File, then choosing the downloaded .xml file returns the following error:

<img width="521" alt="screen shot 2016-04-17 at 9 42 20 am" src="https://cloud.githubusercontent.com/assets/7665736/14585906/108de18a-0487-11e6-8b6f-afc89da13622.png">

**Comment by bowring** [comment]
What igsn?
