### ISSUE TITLE
error ellipses

### ISSUE THREAD

**Issue by AZlaserchron** [CIRDLES/ET_Redux#73]
Hello!  
The issue: as data is being pulled into Redux the uncertainties of 206/207 seem fine, but 206/238 age and errors fly through the roof the longer the acquisition continues.  We witnessed an unknown of 180 Ma, and the very next aliquot, also an unknown, came in at 3.9 Ga.  Subsequently, the aliquot prior (180 Ma) increased to 227 Ma, and uncertainties rose.  It looks like the unknowns are 'correcting' each other.

**Comment by bowring** [comment]
(subject = LASERCHRON ElementII live data acquisition): It is true that all of the uncertainties among the unknowns are correlated across the session to some degree (see [paper](http://onlinelibrary.wiley.com/doi/10.1002/2015GC006097/abstract)).  It may be that we need to force the session fit functions to means and or lines during the acquisition to dampen the swings you mention. The first question is ... at the end of the run after you have discarded bad acquisitions and applied fit functions, do the dates and uncertainties look reasonable?  Please email this session data to me and let's set up another online session to view the live data.

**Comment by bowring** [comment]
This issue has been addressed during Skype calls with @AZlaserchron .
