### ISSUE TITLE
Pulling Standards out for only 6/8 or 6/7 

### ISSUE THREAD

**Issue by AZlaserchron** [CIRDLES/ET_Redux#74]
Hi,

As I have been working with the data table and dealing with poorly behaved standards I have haven't figured out how to remove the standard from just one type of fractionation whether its 6/8 or 6/7. When I remove that fraction it takes it out of both when there is only an issue with one (6/7 or 6/8). Is there any way to select that or choose which one I would like to take a standard out of?

**Comment by bowring** [comment]
No.  A reference material fraction (used to be called standard) is either all in or all out.  @noahmclean can provide further insights.

**Comment by AZlaserchron** [comment]
Sounds good. Makes sense to the fact that if one is off the other wont be as good either for a grain, Thanks!
