### ISSUE TITLE
Having trouble generating weighted means

### ISSUE THREAD

**Issue by ClayFC** [CIRDLES/ET_Redux#75]
Hi,
I'm having trouble generating weighted means. I haven't been able to do this for any of my data sets, I will send an email out with a Redux file.
Thanks!
Clay

**Comment by bowring** [comment]
I received your data files and am exploring this issue ...

**Comment by ClayFC** [comment]
Hi Jim,

I didn't see you replied. Noah showed me how to generate weighted means, maybe there is still a problem generating them when using the downhole method.. If you can email me the login info to the Cirdles channel I'll start working on a detrital spectrum walkthrough!

Thanks,
Clay

**Comment by bowring** [comment]
you should get an invite ... there is only one other video so far

On Wed, Apr 27, 2016 at 7:42 PM, Clay Franklin Campbell <
notifications@github.com> wrote:

> Hi Jim,
>
> I didn't see you replied. Noah showed me how to generate weighted means,
> maybe there is still a problem generating them when using the downhole
> method.. If you can email me the login info to the Cirdles channel I'll
> start working on a detrital spectrum walkthrough!
>
> Thanks,
> Clay
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/CIRDLES/ET_Redux/issues/75#issuecomment-215265385>
>



-- 
Jim Bowring
C. Richard Crosby Distinguished Teaching Co-Chair
Principal Investigator, www.CIRDLES.org, www.github.com/cirdles
GitHub: https://github.com/bowring

Computer Science
College of Charleston
66 George Street
Charleston, SC 29424

Google Voice: 843.608.1399 (preferred)
Google Email: bowring@gmail.com

Office:
Harbor Walk East (360 Concord Street) Room 308
843.953.0805
http://stono.cs.cofc.edu/~bowring/
bowringj@cofc.edu

R. Buckminster Fuller (1972):
If humanity is to survive aboard our planet, it must become universally
literate and preoccupied with inherently cooperative Comprehensive
Anticipatory Design Science in which every human is concerned with
accomplishing the comfortably sustainable well-faring of all other humans.
