### ISSUE TITLE
Rebase `v3.0.4` release code into `master`

### ISSUE THREAD

**Issue by johnzeringue** [CIRDLES/ET_Redux#8]
Since [v3.0.4](https://github.com/CIRDLES/ET_Redux/tree/v3.0.4) has been released to the public and is considered stable, it should be merged into `master`.

I would recommend the following (perhaps in a fresh clone):
- `git checkout master`
- `git pull [upstream master]`, updating `master`
- `git fetch --tags [upstream]`, ensuring that the tag `v3.0.4` is known locally
- `git rebase v3.0.4`, merging the changes without creating a new commit
- `git push [upstream master]`

Note that the parameters in brackets are only used when working from a clone of a fork (and assume that upstream is a remote pointing to `CIRDLES/ET_Redux`).

**Comment by bowring** [comment]
done
