### ISSUE TITLE
Measured data top panel?

### ISSUE THREAD

**Issue by DanCondon** [CIRDLES/ET_Redux#82]
Hi Jim.

We have just upgraded to the new version of ET Redux.  In the new version the top panel that contain the measured ratios has gone.  Some of us find that panel useful so we can look at the measurement uncertainty and the sample/tracer ratio, and practically it helps check reduced data to measurement files (sometimes handy).  Would it be possible to reinstate this?  Noah said people found it distracting but it has some use for some of us, and it could be hidden now you have this drag-able divider?

Cheers,

Dan, Blair, Diana, and Simon.

**Comment by bowring** [comment]
Dan-
In Thailand til June. Try customizing data table / reports view for now.

Jim

On Thursday, May 12, 2016, DanCondon <notifications@github.com> wrote:

> Hi Jim.
>
> We have just upgraded to the new version of ET Redux. In the new version
> the top panel that contain the measured ratios has gone. Some of us find
> that panel useful so we can look at the measurement uncertainty and the
> sample/tracer ratio, and practically it helps check reduced data to
> measurement files (sometimes handy). Would it be possible to reinstate
> this? Noah said people found it distracting but it has some use for some of
> us, and it could be hidden now you have this drag-able divider?
>
> Cheers,
>
> Dan, Blair, Diana, and Simon.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/CIRDLES/ET_Redux/issues/82>
>


-- 
Jim Bowring
C. Richard Crosby Distinguished Teaching Co-Chair
Principal Investigator, www.CIRDLES.org, www.github.com/cirdles
GitHub: https://github.com/bowring

Computer Science
College of Charleston
66 George Street
Charleston, SC 29424

Google Voice: 843.608.1399 (preferred)
Google Email: bowring@gmail.com

Office:
Harbor Walk East (360 Concord Street) Room 308
843.953.0805
http://stono.cs.cofc.edu/~bowring/
bowringj@cofc.edu

R. Buckminster Fuller (1972):
If humanity is to survive aboard our planet, it must become universally
literate and preoccupied with inherently cooperative Comprehensive
Anticipatory Design Science in which every human is concerned with
accomplishing the comfortably sustainable well-faring of all other humans.

**Comment by bowring** [comment]
back now, let's Skype sometime?  interesting story about Sam, too!

On Thu, May 12, 2016 at 7:12 PM, Jim Bowring <bowring@gmail.com> wrote:

> Dan-
> In Thailand til June. Try customizing data table / reports view for now.
>
> Jim
>
>
> On Thursday, May 12, 2016, DanCondon <notifications@github.com> wrote:
>
>> Hi Jim.
>>
>> We have just upgraded to the new version of ET Redux. In the new version
>> the top panel that contain the measured ratios has gone. Some of us find
>> that panel useful so we can look at the measurement uncertainty and the
>> sample/tracer ratio, and practically it helps check reduced data to
>> measurement files (sometimes handy). Would it be possible to reinstate
>> this? Noah said people found it distracting but it has some use for some of
>> us, and it could be hidden now you have this drag-able divider?
>>
>> Cheers,
>>
>> Dan, Blair, Diana, and Simon.
>>
>> —
>> You are receiving this because you are subscribed to this thread.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/CIRDLES/ET_Redux/issues/82>
>>
>
>
> --
> Jim Bowring
> C. Richard Crosby Distinguished Teaching Co-Chair
> Principal Investigator, www.CIRDLES.org, www.github.com/cirdles
> GitHub: https://github.com/bowring
>
> Computer Science
> College of Charleston
> 66 George Street
> Charleston, SC 29424
>
> Google Voice: 843.608.1399 (preferred)
> Google Email: bowring@gmail.com
>
> Office:
> Harbor Walk East (360 Concord Street) Room 308
> 843.953.0805
> http://stono.cs.cofc.edu/~bowring/
> bowringj@cofc.edu
>
> R. Buckminster Fuller (1972):
> If humanity is to survive aboard our planet, it must become universally
> literate and preoccupied with inherently cooperative Comprehensive
> Anticipatory Design Science in which every human is concerned with
> accomplishing the comfortably sustainable well-faring of all other humans.
>
>


-- 
Jim Bowring
C. Richard Crosby Distinguished Teaching Co-Chair
Principal Investigator, www.CIRDLES.org, www.github.com/cirdles
GitHub: https://github.com/bowring

Computer Science
College of Charleston
66 George Street
Charleston, SC 29424

Google Voice: 843.608.1399 (preferred)
Google Email: bowring@gmail.com

Office:
Harbor Walk East (360 Concord Street) Room 308
843.953.0805
http://stono.cs.cofc.edu/~bowring/
bowringj@cofc.edu

R. Buckminster Fuller (1972):
If humanity is to survive aboard our planet, it must become universally
literate and preoccupied with inherently cooperative Comprehensive
Anticipatory Design Science in which every human is concerned with
accomplishing the comfortably sustainable well-faring of all other humans.
