### ISSUE TITLE
ADD: Most recent acquisition age window in live data reduction

### ISSUE THREAD

**Issue by AZlaserchron** [CIRDLES/ET_Redux#85]
This corresponds to the loading time issue we have been dealing with. When a new fraction is added to the live data table it goes to the bottom of its designated column. This should continue, but we would like there to be a window that shows us the name of the last acquisition along with the 6/8, 7/5, and 7/6 ages and uncertainties. This would be helpful when redux begins its infinite loop when we can't even scroll down to the data table. If the ages and uncertainties were added to a box under the concordia so we can see them with out scrolling down that would be especially useful.

**Comment by bowring** [comment]
This should be resolved with a solution to the previous issue.  Thank you
for being a super-user and reporting in writing!
