### ISSUE TITLE
Resetting of filters in live data reduction

### ISSUE THREAD

**Issue by AZlaserchron** [CIRDLES/ET_Redux#86]
When there is a new fraction added to the data table both the concordia and PDP are refreshed to add that new fraction. When the plots reset they automatically revert the positive and negative discordance filters back to 100%. This doesn't make sense as you only have a short amount of time to view the changes because of the next acquisition being added so soon. We would want the filters to stay at the values we give them until we change them again or turn them off. When a new fraction is added it will only be plotted if it corresponds to the set filter values. This will give us a much better visualization of data the data if the filters aren't constantly being reset.

**Comment by bowring** [comment]
Good points!.
