### ISSUE TITLE
Thermo Finnigan Neptune data

### ISSUE THREAD

**Issue by Felipe-UnB** [CIRDLES/ET_Redux#87]
Dear Mr. Bowring, I'd like to know if ET_Redux is currently able to handle data from Thermo Finningan Neptune? 

Felipe

**Comment by bowring** [comment]
Not yet ... would love to add your machine to the workflow.  Can you send under separate cover to me (bowring@gmail.com) a sample run with metadata so we can understand what's involved?  Thanks for your interest.

**Comment by Felipe-UnB** [comment]
Mr Bowring, I'll prepare the data but before I need an information before. The data from Neptune is described by 3 files (with extensions .dat, .log and .TDT) which can be read only by Evaluation, one of the programs used to operate the equipment. We have to use Evaluation to export this data to tab delimited files in order to process them with Excel. Which files would ET-Redux read? The 3 original ones or the exported tab-delimited?

**Comment by bowring** [comment]
We have software to read the dat files from the elementII so I hope it works here for these files as well.  Send me a couple dat files to experiment with.

**Comment by AZlaserchron** [comment]
Sent some more dat files through dropbox. Let me know if you need any more.


-Dan

________________________________

**Comment by bowring** [comment]
Not seeing dropbox files ...

**Comment by Felipe-UnB** [comment]
Files sent to your e-mail, Mr. Bowring.

**Comment by bowring** [comment]
Our python script can't read your .dat files (see separate email) so we will have to work from whatever files you can generate and supply as an example.
