### ISSUE TITLE
Some cosmetic upgrades for live reduction

### ISSUE THREAD

**Issue by AZlaserchron** [CIRDLES/ET_Redux#94]
These are just a few simple cosmetic adjustments George has request for the live data reduction window. 

- [ ] Adding a full screen button to max and min the size of the window easily. 

- [ ] Removing the R33 and SL analysis from the PDP plot so it only displays the unknowns.
   This will make the view easier for the visiting researchers who are unsure about using the software.

- [ ] Reducing the size of the report table if we choose not to have all the other columns active and have the slider bar to move up and down in the table correspond to the resizing.
   This will make our scrolling throughout the data table easier and more efficient.

- [ ] Last, having a most recent age window that displays the most recent analysis with the following information: sample name, 6/8 age and uncertainty, 7/5 age and uncertainty, 6/7 age and uncertainty.
    This would be great for the visiting researchers so they don't have to search for the most recent           grain and have the views refresh on them and have to start their search over. When the views refresh the report table defaults back to the top starting with the FC grains. Having this window would make the viewing much easier and less stressful to visitors.

Other than just those cosmetic issues both the fast uncertainties and full propagation are working incredibly. The speed of which the data comes in is incredible, and as of these past two weeks the fractional plots have been looking excellent. George has also noticed that the uncertainties in the live views are almost 4 times the uncertainties we get in agecalc, for all three different ages. I have to still work more with the actual data manager mode to see if I can bring those uncertainties closer to agecalc. 

Thanks;
-Dan

**Comment by bowring** [comment]
These are good suggestions.  You can manage the report table now using the supplied button and save off any number of customized table views you like.  Noah and George are working on the uncertainty issue relative to handling count vs analog modes - it involves getting more info from the Element II manufacturer.  Don't assume the AgeCalc uncertainties are correct, however.

Work is proceeding on your requests.
